export {
  classifyContest,
  getContestNameLabel,
  getContestPriority,
  contestTypePriorities,
  addContestNameToTaskIndex,
  isWorldTourFinals,
  getWorldTourFinalsLabel,
  getPastContestLabel,
  getJoiContestLabel,
  getAtCoderUniversityContestLabel,
  getAojContestLabel,
  AOJ_COURSES,
  getPrefixForAojCourses,
  getContestPrefixes,
  regexForJag,
  regexForAojUniversity,
  PAST_TRANSLATIONS,
} from '$lib/contests/utils/contest';
