services:
  web:
    build: .
    ports:
      - 5173:5173
    tty: true
    volumes:
      - .:/usr/src/app:cached
      - ./node_modules:/usr/src/app/node_modules:cached
    environment:
      - NODE_ENV=development
