// See:
// https://kenkoooo.com/atcoder/resources/problems.json
export const tasks = [
  {
    id: 'abc327_g',
    contest_id: 'abc327',
    problem_index: 'G',
    name: 'Many Good Tuple Problems',
    title: 'G. Many Good Tuple Problems',
    grade: 'D5',
  },
  {
    id: 'abc327_f',
    contest_id: 'abc327',
    problem_index: 'F',
    name: 'Apples',
    title: 'F. Apples',
    grade: 'D2',
  },
  {
    id: 'abc327_e',
    contest_id: 'abc327',
    problem_index: 'E',
    name: 'Maximize Rating',
    title: 'E. Maximize Rating',
    grade: 'D1',
  },
  {
    id: 'abc327_d',
    contest_id: 'abc327',
    problem_index: 'D',
    name: 'Good Tuple Problem',
    title: 'D. Good Tuple Problem',
    grade: 'Q2',
  },
  {
    id: 'abc327_c',
    contest_id: 'abc327',
    problem_index: 'C',
    name: 'Number Place',
    title: 'C. Number Place',
    grade: 'Q5',
  },
  {
    id: 'abc327_b',
    contest_id: 'abc327',
    problem_index: 'B',
    name: 'A^A',
    title: 'B. A^A',
    grade: 'Q6',
  },
  {
    id: 'abc327_a',
    contest_id: 'abc327',
    problem_index: 'A',
    name: 'ab',
    title: 'A. ab',
    grade: 'Q7',
  },
  {
    id: 'abc326_g',
    contest_id: 'abc326',
    problem_index: 'G',
    name: 'Unlock Achievement',
    title: 'G. Unlock Achievement',
    grade: 'D4',
  },
  {
    id: 'abc326_f',
    contest_id: 'abc326',
    problem_index: 'F',
    name: 'Robot Rotation',
    title: 'F. Robot Rotation',
    grade: 'D2',
  },
  {
    id: 'abc326_e',
    contest_id: 'abc326',
    problem_index: 'E',
    name: 'Revenge of "The Salary of AtCoder Inc."',
    title: 'E. Revenge of "The Salary of AtCoder Inc."',
    grade: 'D1',
  },
  {
    id: 'abc326_d',
    contest_id: 'abc326',
    problem_index: 'D',
    name: 'ABC Puzzle',
    title: 'D. ABC Puzzle',
    grade: 'D1',
  },
  {
    id: 'abc326_c',
    contest_id: 'abc326',
    problem_index: 'C',
    name: 'Peak',
    title: 'C. Peak',
    grade: 'Q4',
  },
  {
    id: 'abc326_b',
    contest_id: 'abc326',
    problem_index: 'B',
    name: '326-like Numbers',
    title: 'B. 326-like Numbers',
    grade: 'Q7',
  },
  {
    id: 'abc326_a',
    contest_id: 'abc326',
    problem_index: 'A',
    name: '2UP3DOWN',
    title: 'A. 2UP3DOWN',
    grade: 'Q7',
  },
  {
    id: 'abc325_g',
    contest_id: 'abc325',
    problem_index: 'G',
    name: 'offence',
    title: 'G. offence',
    grade: 'D3',
  },
  {
    id: 'abc325_f',
    contest_id: 'abc325',
    problem_index: 'F',
    name: 'Sensor Optimization Dilemma ',
    title: 'F. Sensor Optimization Dilemma ',
    grade: 'D2',
  },
  {
    id: 'abc325_e',
    contest_id: 'abc325',
    problem_index: 'E',
    name: 'Our clients, please wait a moment',
    title: 'E. Our clients, please wait a moment',
    grade: 'Q1',
  },
  {
    id: 'abc325_d',
    contest_id: 'abc325',
    problem_index: 'D',
    name: 'Printing Machine',
    title: 'D. Printing Machine',
    grade: 'D1',
  },
  {
    id: 'abc325_c',
    contest_id: 'abc325',
    problem_index: 'C',
    name: 'Sensors',
    title: 'C. Sensors',
    grade: 'Q3',
  },
  {
    id: 'abc325_b',
    contest_id: 'abc325',
    problem_index: 'B',
    name: 'World Meeting',
    title: 'B. World Meeting',
    grade: 'Q5',
  },
  {
    id: 'abc325_a',
    contest_id: 'abc325',
    problem_index: 'A',
    name: 'Takahashi san',
    title: 'A. Takahashi san',
    grade: 'Q8',
  },
  {
    id: 'abc324_g',
    contest_id: 'abc324',
    problem_index: 'G',
    name: 'Generate Arrays',
    title: 'G. Generate Arrays',
    grade: 'D4',
  },
  {
    id: 'abc324_f',
    contest_id: 'abc324',
    problem_index: 'F',
    name: 'Beautiful Path',
    title: 'F. Beautiful Path',
    grade: 'D2',
  },
  {
    id: 'abc324_e',
    contest_id: 'abc324',
    problem_index: 'E',
    name: 'Joint Two Strings',
    title: 'E. Joint Two Strings',
    grade: 'Q1',
  },
  {
    id: 'abc324_d',
    contest_id: 'abc324',
    problem_index: 'D',
    name: 'Square Permutation',
    title: 'D. Square Permutation',
    grade: 'Q2',
  },
  {
    id: 'abc324_c',
    contest_id: 'abc324',
    problem_index: 'C',
    name: 'Error Correction',
    title: 'C. Error Correction',
    grade: 'Q2',
  },
  {
    id: 'abc324_b',
    contest_id: 'abc324',
    problem_index: 'B',
    name: '3-smooth Numbers',
    title: 'B. 3-smooth Numbers',
    grade: 'Q6',
  },
  {
    id: 'abc324_a',
    contest_id: 'abc324',
    problem_index: 'A',
    name: 'Same',
    title: 'A. Same',
    grade: 'Q7',
  },
  {
    id: 'abc323_g',
    contest_id: 'abc323',
    problem_index: 'G',
    name: 'Inversion of Tree',
    title: 'G. Inversion of Tree',
    grade: 'D5',
  },
  {
    id: 'abc323_f',
    contest_id: 'abc323',
    problem_index: 'F',
    name: 'Push and Carry',
    title: 'F. Push and Carry',
    grade: 'D1',
  },
  {
    id: 'abc323_e',
    contest_id: 'abc323',
    problem_index: 'E',
    name: 'Playlist',
    title: 'E. Playlist',
    grade: 'D1',
  },
  {
    id: 'abc323_d',
    contest_id: 'abc323',
    problem_index: 'D',
    name: 'Merge Slimes',
    title: 'D. Merge Slimes',
    grade: 'Q2',
  },
  {
    id: 'abc323_c',
    contest_id: 'abc323',
    problem_index: 'C',
    name: 'World Tour Finals',
    title: 'C. World Tour Finals',
    grade: 'Q4',
  },
  {
    id: 'abc323_b',
    contest_id: 'abc323',
    problem_index: 'B',
    name: 'Round-Robin Tournament',
    title: 'B. Round-Robin Tournament',
    grade: 'Q6',
  },
  {
    id: 'abc323_a',
    contest_id: 'abc323',
    problem_index: 'A',
    name: 'Weak Beats',
    title: 'A. Weak Beats',
    grade: 'Q7',
  },
  {
    id: 'abc322_g',
    contest_id: 'abc322',
    problem_index: 'G',
    name: 'Two Kinds of Base',
    title: 'G. Two Kinds of Base',
    grade: 'D4',
  },
  {
    id: 'abc322_f',
    contest_id: 'abc322',
    problem_index: 'F',
    name: 'Vacation Query',
    title: 'F. Vacation Query',
    grade: 'D2',
  },
  {
    id: 'abc322_e',
    contest_id: 'abc322',
    problem_index: 'E',
    name: 'Product Development',
    title: 'E. Product Development',
    grade: 'Q1',
  },
  {
    id: 'abc322_d',
    contest_id: 'abc322',
    problem_index: 'D',
    name: 'Polyomino',
    title: 'D. Polyomino',
    grade: 'Q1',
  },
  {
    id: 'abc322_c',
    contest_id: 'abc322',
    problem_index: 'C',
    name: 'Festival',
    title: 'C. Festival',
    grade: 'Q5',
  },
  {
    id: 'abc322_b',
    contest_id: 'abc322',
    problem_index: 'B',
    name: 'Prefix and Suffix',
    title: 'B. Prefix and Suffix',
    grade: 'Q6',
  },
  {
    id: 'abc322_a',
    contest_id: 'abc322',
    problem_index: 'A',
    name: 'First ABC 2',
    title: 'A. First ABC 2',
    grade: 'Q7',
  },
  {
    id: 'abc321_g',
    contest_id: 'abc321',
    problem_index: 'G',
    name: 'Electric Circuit',
    title: 'G. Electric Circuit',
    grade: 'D4',
  },
  {
    id: 'abc321_f',
    contest_id: 'abc321',
    problem_index: 'F',
    name: '#(subset sum = K) with Add and Erase ',
    title: 'F. #(subset sum = K) with Add and Erase ',
    grade: 'D2',
  },
  {
    id: 'abc321_e',
    contest_id: 'abc321',
    problem_index: 'E',
    name: 'Complete Binary Tree',
    title: 'E. Complete Binary Tree',
    grade: 'D2',
  },
  {
    id: 'abc321_d',
    contest_id: 'abc321',
    problem_index: 'D',
    name: 'Set Menu',
    title: 'D. Set Menu',
    grade: 'Q2',
  },
  {
    id: 'abc321_c',
    contest_id: 'abc321',
    problem_index: 'C',
    name: '321-like Searcher',
    title: 'C. 321-like Searcher',
    grade: 'Q2',
  },
  {
    id: 'abc321_b',
    contest_id: 'abc321',
    problem_index: 'B',
    name: 'Cutoff',
    title: 'B. Cutoff',
    grade: 'Q4',
  },
  {
    id: 'abc321_a',
    contest_id: 'abc321',
    problem_index: 'A',
    name: '321-like Checker',
    title: 'A. 321-like Checker',
    grade: 'Q7',
  },
  {
    id: 'abc320_g',
    contest_id: 'abc320',
    problem_index: 'G',
    name: 'Slot Strategy 2 (Hard)',
    title: 'G. Slot Strategy 2 (Hard)',
  },
  {
    id: 'abc320_f',
    contest_id: 'abc320',
    problem_index: 'F',
    name: 'Fuel Round Trip',
    title: 'F. Fuel Round Trip',
  },
  {
    id: 'abc320_e',
    contest_id: 'abc320',
    problem_index: 'E',
    name: 'Somen Nagashi',
    title: 'E. Somen Nagashi',
  },
  {
    id: 'abc320_d',
    contest_id: 'abc320',
    problem_index: 'D',
    name: 'Relative Position',
    title: 'D. Relative Position',
  },
  {
    id: 'abc320_c',
    contest_id: 'abc320',
    problem_index: 'C',
    name: 'Slot Strategy 2 (Easy)',
    title: 'C. Slot Strategy 2 (Easy)',
  },
  {
    id: 'abc320_b',
    contest_id: 'abc320',
    problem_index: 'B',
    name: 'Longest Palindrome',
    title: 'B. Longest Palindrome',
    grade: 'Q6',
  },
  {
    id: 'abc320_a',
    contest_id: 'abc320',
    problem_index: 'A',
    name: 'Leyland Number',
    title: 'A. Leyland Number',
    grade: 'Q7',
  },
  {
    id: 'abc319_g',
    contest_id: 'abc319',
    problem_index: 'G',
    name: 'Counting Shortest Paths',
    title: 'G. Counting Shortest Paths',
  },
  {
    id: 'abc319_f',
    contest_id: 'abc319',
    problem_index: 'F',
    name: 'Fighter Takahashi',
    title: 'F. Fighter Takahashi',
  },
  {
    id: 'abc319_e',
    contest_id: 'abc319',
    problem_index: 'E',
    name: 'Bus Stops',
    title: 'E. Bus Stops',
  },
  {
    id: 'abc319_d',
    contest_id: 'abc319',
    problem_index: 'D',
    name: 'Minimum Width',
    title: 'D. Minimum Width',
  },
  {
    id: 'abc319_c',
    contest_id: 'abc319',
    problem_index: 'C',
    name: 'False Hope',
    title: 'C. False Hope',
  },
  {
    id: 'abc319_b',
    contest_id: 'abc319',
    problem_index: 'B',
    name: 'Measure',
    title: 'B. Measure',
    grade: 'Q6',
  },
  {
    id: 'abc319_a',
    contest_id: 'abc319',
    problem_index: 'A',
    name: 'Legendary Players',
    title: 'A. Legendary Players',
    grade: 'Q7',
  },
  {
    id: 'abc318_h',
    contest_id: 'abc318',
    problem_index: 'Ex',
    name: 'Count Strong Test Cases',
    title: 'Ex. Count Strong Test Cases',
  },
  {
    id: 'abc318_g',
    contest_id: 'abc318',
    problem_index: 'G',
    name: 'Typical Path Problem',
    title: 'G. Typical Path Problem',
  },
  {
    id: 'abc318_f',
    contest_id: 'abc318',
    problem_index: 'F',
    name: 'Octopus',
    title: 'F. Octopus',
  },
  {
    id: 'abc318_e',
    contest_id: 'abc318',
    problem_index: 'E',
    name: 'Sandwiches',
    title: 'E. Sandwiches',
  },
  {
    id: 'abc318_d',
    contest_id: 'abc318',
    problem_index: 'D',
    name: 'General Weighted Max Matching',
    title: 'D. General Weighted Max Matching',
  },
  {
    id: 'abc318_c',
    contest_id: 'abc318',
    problem_index: 'C',
    name: 'Blue Spring',
    title: 'C. Blue Spring',
  },
  {
    id: 'abc318_b',
    contest_id: 'abc318',
    problem_index: 'B',
    name: 'Overlapping sheets',
    title: 'B. Overlapping sheets',
  },
  {
    id: 'abc318_a',
    contest_id: 'abc318',
    problem_index: 'A',
    name: 'Full Moon',
    title: 'A. Full Moon',
    grade: 'Q7',
  },
  {
    id: 'abc317_h',
    contest_id: 'abc317',
    problem_index: 'Ex',
    name: 'Walk',
    title: 'Ex. Walk',
  },
  {
    id: 'abc317_g',
    contest_id: 'abc317',
    problem_index: 'G',
    name: 'Rearranging',
    title: 'G. Rearranging',
  },
  {
    id: 'abc317_f',
    contest_id: 'abc317',
    problem_index: 'F',
    name: 'Nim',
    title: 'F. Nim',
  },
  {
    id: 'abc317_e',
    contest_id: 'abc317',
    problem_index: 'E',
    name: 'Avoid Eye Contact',
    title: 'E. Avoid Eye Contact',
  },
  {
    id: 'abc317_d',
    contest_id: 'abc317',
    problem_index: 'D',
    name: 'President',
    title: 'D. President',
  },
  {
    id: 'abc317_c',
    contest_id: 'abc317',
    problem_index: 'C',
    name: 'Remembering the Days',
    title: 'C. Remembering the Days',
  },
  {
    id: 'abc317_b',
    contest_id: 'abc317',
    problem_index: 'B',
    name: 'MissingNo.',
    title: 'B. MissingNo.',
  },
  {
    id: 'abc317_a',
    contest_id: 'abc317',
    problem_index: 'A',
    name: 'Potions',
    title: 'A. Potions',
    grade: 'Q7',
  },
  {
    id: 'abc315_h',
    contest_id: 'abc315',
    problem_index: 'Ex',
    name: 'Typical Convolution Problem',
    title: 'Ex. Typical Convolution Problem',
  },
  {
    id: 'abc315_g',
    contest_id: 'abc315',
    problem_index: 'G',
    name: 'Ai + Bj + Ck = X (1 <= i, j, k <= N)',
    title: 'G. Ai + Bj + Ck = X (1 <= i, j, k <= N)',
  },
  {
    id: 'abc315_f',
    contest_id: 'abc315',
    problem_index: 'F',
    name: 'Shortcuts',
    title: 'F. Shortcuts',
    grade: 'D1',
  },
  {
    id: 'abc315_e',
    contest_id: 'abc315',
    problem_index: 'E',
    name: 'Prerequisites',
    title: 'E. Prerequisites',
  },
  {
    id: 'abc315_d',
    contest_id: 'abc315',
    problem_index: 'D',
    name: 'Magical Cookies',
    title: 'D. Magical Cookies',
  },
  {
    id: 'abc315_c',
    contest_id: 'abc315',
    problem_index: 'C',
    name: 'Flavors',
    title: 'C. Flavors',
  },
  {
    id: 'abc315_b',
    contest_id: 'abc315',
    problem_index: 'B',
    name: 'The Middle Day',
    title: 'B. The Middle Day',
  },
  {
    id: 'abc315_a',
    contest_id: 'abc315',
    problem_index: 'A',
    name: 'tcdr',
    title: 'A. tcdr',
    grade: 'Q8',
  },
  {
    id: 'abc314_h',
    contest_id: 'abc314',
    problem_index: 'Ex',
    name: 'Disk and Segments',
    title: 'Ex. Disk and Segments',
  },
  {
    id: 'abc314_g',
    contest_id: 'abc314',
    problem_index: 'G',
    name: 'Amulets',
    title: 'G. Amulets',
  },
  {
    id: 'abc314_f',
    contest_id: 'abc314',
    problem_index: 'F',
    name: 'A Certain Game',
    title: 'F. A Certain Game',
  },
  {
    id: 'abc314_e',
    contest_id: 'abc314',
    problem_index: 'E',
    name: 'Roulettes',
    title: 'E. Roulettes',
  },
  {
    id: 'abc314_d',
    contest_id: 'abc314',
    problem_index: 'D',
    name: 'LOWER',
    title: 'D. LOWER',
  },
  {
    id: 'abc314_c',
    contest_id: 'abc314',
    problem_index: 'C',
    name: 'Rotate Colored Subsequence',
    title: 'C. Rotate Colored Subsequence',
  },
  {
    id: 'abc314_b',
    contest_id: 'abc314',
    problem_index: 'B',
    name: 'Roulette',
    title: 'B. Roulette',
  },
  {
    id: 'abc314_a',
    contest_id: 'abc314',
    problem_index: 'A',
    name: '3.14',
    title: 'A. 3.14',
    grade: 'Q7',
  },
  {
    id: 'abc313_h',
    contest_id: 'abc313',
    problem_index: 'Ex',
    name: 'Group Photo',
    title: 'Ex. Group Photo',
  },
  {
    id: 'abc313_g',
    contest_id: 'abc313',
    problem_index: 'G',
    name: 'Redistribution of Piles',
    title: 'G. Redistribution of Piles',
  },
  {
    id: 'abc313_f',
    contest_id: 'abc313',
    problem_index: 'F',
    name: 'Flip Machines',
    title: 'F. Flip Machines',
  },
  {
    id: 'abc313_e',
    contest_id: 'abc313',
    problem_index: 'E',
    name: 'Duplicate',
    title: 'E. Duplicate',
  },
  {
    id: 'abc313_d',
    contest_id: 'abc313',
    problem_index: 'D',
    name: 'Odd or Even',
    title: 'D. Odd or Even',
  },
  {
    id: 'abc313_c',
    contest_id: 'abc313',
    problem_index: 'C',
    name: 'Approximate Equalization 2',
    title: 'C. Approximate Equalization 2',
  },
  {
    id: 'abc313_b',
    contest_id: 'abc313',
    problem_index: 'B',
    name: 'Who is Saikyo?',
    title: 'B. Who is Saikyo?',
    grade: 'Q4',
  },
  {
    id: 'abc313_a',
    contest_id: 'abc313',
    problem_index: 'A',
    name: 'To Be Saikyo',
    title: 'A. To Be Saikyo',
    grade: 'Q6',
  },
  {
    id: 'abc312_h',
    contest_id: 'abc312',
    problem_index: 'Ex',
    name: 'snukesnuke',
    title: 'Ex. snukesnuke',
  },
  {
    id: 'abc312_g',
    contest_id: 'abc312',
    problem_index: 'G',
    name: 'Avoid Straight Line',
    title: 'G. Avoid Straight Line',
  },
  {
    id: 'abc312_f',
    contest_id: 'abc312',
    problem_index: 'F',
    name: 'Cans and Openers',
    title: 'F. Cans and Openers',
  },
  {
    id: 'abc312_e',
    contest_id: 'abc312',
    problem_index: 'E',
    name: 'Tangency of Cuboids ',
    title: 'E. Tangency of Cuboids ',
  },
  {
    id: 'abc312_d',
    contest_id: 'abc312',
    problem_index: 'D',
    name: 'Count Bracket Sequences',
    title: 'D. Count Bracket Sequences',
  },
  {
    id: 'abc312_c',
    contest_id: 'abc312',
    problem_index: 'C',
    name: 'Invisible Hand',
    title: 'C. Invisible Hand',
  },
  {
    id: 'abc312_b',
    contest_id: 'abc312',
    problem_index: 'B',
    name: 'TaK Code',
    title: 'B. TaK Code',
  },
  {
    id: 'abc312_a',
    contest_id: 'abc312',
    problem_index: 'A',
    name: 'Chord',
    title: 'A. Chord',
    grade: 'Q8',
  },
  {
    id: 'abc311_h',
    contest_id: 'abc311',
    problem_index: 'Ex',
    name: 'Many Illumination Plans',
    title: 'Ex. Many Illumination Plans',
  },
  {
    id: 'abc311_g',
    contest_id: 'abc311',
    problem_index: 'G',
    name: 'One More Grid Task',
    title: 'G. One More Grid Task',
  },
  {
    id: 'abc311_f',
    contest_id: 'abc311',
    problem_index: 'F',
    name: 'Yet Another Grid Task',
    title: 'F. Yet Another Grid Task',
  },
  {
    id: 'abc311_e',
    contest_id: 'abc311',
    problem_index: 'E',
    name: 'Defect-free Squares',
    title: 'E. Defect-free Squares',
  },
  {
    id: 'abc311_d',
    contest_id: 'abc311',
    problem_index: 'D',
    name: 'Grid Ice Floor',
    title: 'D. Grid Ice Floor',
  },
  {
    id: 'abc311_c',
    contest_id: 'abc311',
    problem_index: 'C',
    name: 'Find it!',
    title: 'C. Find it!',
  },
  {
    id: 'abc311_b',
    contest_id: 'abc311',
    problem_index: 'B',
    name: 'Vacation Together',
    title: 'B. Vacation Together',
    grade: 'Q6',
  },
  {
    id: 'abc311_a',
    contest_id: 'abc311',
    problem_index: 'A',
    name: 'First ABC',
    title: 'A. First ABC',
    grade: 'Q7',
  },
  {
    id: 'abc310_h',
    contest_id: 'abc310',
    problem_index: 'Ex',
    name: 'Negative Cost',
    title: 'Ex. Negative Cost',
  },
  {
    id: 'abc310_g',
    contest_id: 'abc310',
    problem_index: 'G',
    name: 'Takahashi And Pass-The-Ball Game',
    title: 'G. Takahashi And Pass-The-Ball Game',
  },
  {
    id: 'abc310_f',
    contest_id: 'abc310',
    problem_index: 'F',
    name: 'Make 10 Again',
    title: 'F. Make 10 Again',
  },
  {
    id: 'abc310_e',
    contest_id: 'abc310',
    problem_index: 'E',
    name: 'NAND repeatedly',
    title: 'E. NAND repeatedly',
  },
  {
    id: 'abc310_d',
    contest_id: 'abc310',
    problem_index: 'D',
    name: 'Peaceful Teams',
    title: 'D. Peaceful Teams',
  },
  {
    id: 'abc310_c',
    contest_id: 'abc310',
    problem_index: 'C',
    name: 'Reversible',
    title: 'C. Reversible',
  },
  {
    id: 'abc310_b',
    contest_id: 'abc310',
    problem_index: 'B',
    name: 'Strictly Superior',
    title: 'B. Strictly Superior',
  },
  {
    id: 'abc310_a',
    contest_id: 'abc310',
    problem_index: 'A',
    name: 'Order Something Else',
    title: 'A. Order Something Else',
    grade: 'Q7',
  },
  {
    id: 'abc309_h',
    contest_id: 'abc309',
    problem_index: 'Ex',
    name: 'Simple Path Counting Problem',
    title: 'Ex. Simple Path Counting Problem',
  },
  {
    id: 'abc309_g',
    contest_id: 'abc309',
    problem_index: 'G',
    name: 'Ban Permutation',
    title: 'G. Ban Permutation',
  },
  {
    id: 'abc309_f',
    contest_id: 'abc309',
    problem_index: 'F',
    name: 'Box in Box',
    title: 'F. Box in Box',
  },
  {
    id: 'abc309_e',
    contest_id: 'abc309',
    problem_index: 'E',
    name: 'Family and Insurance',
    title: 'E. Family and Insurance',
  },
  {
    id: 'abc309_d',
    contest_id: 'abc309',
    problem_index: 'D',
    name: 'Add One Edge',
    title: 'D. Add One Edge',
  },
  {
    id: 'abc309_c',
    contest_id: 'abc309',
    problem_index: 'C',
    name: 'Medicine',
    title: 'C. Medicine',
  },
  {
    id: 'abc309_b',
    contest_id: 'abc309',
    problem_index: 'B',
    name: 'Rotate',
    title: 'B. Rotate',
    grade: 'Q5',
  },
  {
    id: 'abc309_a',
    contest_id: 'abc309',
    problem_index: 'A',
    name: 'Nine',
    title: 'A. Nine',
    grade: 'Q7',
  },
  {
    id: 'abc308_h',
    contest_id: 'abc308',
    problem_index: 'Ex',
    name: 'Make Q',
    title: 'Ex. Make Q',
  },
  {
    id: 'abc308_g',
    contest_id: 'abc308',
    problem_index: 'G',
    name: 'Minimum Xor Pair Query',
    title: 'G. Minimum Xor Pair Query',
  },
  {
    id: 'abc308_f',
    contest_id: 'abc308',
    problem_index: 'F',
    name: 'Vouchers',
    title: 'F. Vouchers',
  },
  {
    id: 'abc308_e',
    contest_id: 'abc308',
    problem_index: 'E',
    name: 'MEX',
    title: 'E. MEX',
  },
  {
    id: 'abc308_d',
    contest_id: 'abc308',
    problem_index: 'D',
    name: 'Snuke Maze',
    title: 'D. Snuke Maze',
  },
  {
    id: 'abc308_c',
    contest_id: 'abc308',
    problem_index: 'C',
    name: 'Standings',
    title: 'C. Standings',
    grade: 'Q3',
  },
  {
    id: 'abc308_b',
    contest_id: 'abc308',
    problem_index: 'B',
    name: 'Default Price',
    title: 'B. Default Price',
  },
  {
    id: 'abc308_a',
    contest_id: 'abc308',
    problem_index: 'A',
    name: 'New Scheme',
    title: 'A. New Scheme',
    grade: 'Q7',
  },
  {
    id: 'abc307_h',
    contest_id: 'abc307',
    problem_index: 'Ex',
    name: 'Marquee',
    title: 'Ex. Marquee',
  },
  {
    id: 'abc307_g',
    contest_id: 'abc307',
    problem_index: 'G',
    name: 'Approximate Equalization',
    title: 'G. Approximate Equalization',
  },
  {
    id: 'abc307_f',
    contest_id: 'abc307',
    problem_index: 'F',
    name: 'Virus 2',
    title: 'F. Virus 2',
  },
  {
    id: 'abc307_e',
    contest_id: 'abc307',
    problem_index: 'E',
    name: 'Distinct Adjacent',
    title: 'E. Distinct Adjacent',
  },
  {
    id: 'abc307_d',
    contest_id: 'abc307',
    problem_index: 'D',
    name: 'Mismatched Parentheses',
    title: 'D. Mismatched Parentheses',
  },
  {
    id: 'abc307_c',
    contest_id: 'abc307',
    problem_index: 'C',
    name: 'Ideal Sheet',
    title: 'C. Ideal Sheet',
  },
  {
    id: 'abc307_b',
    contest_id: 'abc307',
    problem_index: 'B',
    name: 'racecar',
    title: 'B. racecar',
  },
  {
    id: 'abc307_a',
    contest_id: 'abc307',
    problem_index: 'A',
    name: 'Weekly Records',
    title: 'A. Weekly Records',
    grade: 'Q7',
  },
  {
    id: 'abc306_h',
    contest_id: 'abc306',
    problem_index: 'Ex',
    name: 'Balance Scale',
    title: 'Ex. Balance Scale',
  },
  {
    id: 'abc306_g',
    contest_id: 'abc306',
    problem_index: 'G',
    name: 'Return to 1',
    title: 'G. Return to 1',
  },
  {
    id: 'abc306_f',
    contest_id: 'abc306',
    problem_index: 'F',
    name: 'Merge Sets',
    title: 'F. Merge Sets',
  },
  {
    id: 'abc306_e',
    contest_id: 'abc306',
    problem_index: 'E',
    name: 'Best Performances',
    title: 'E. Best Performances',
  },
  {
    id: 'abc306_d',
    contest_id: 'abc306',
    problem_index: 'D',
    name: 'Poisonous Full-Course',
    title: 'D. Poisonous Full-Course',
  },
  {
    id: 'abc306_c',
    contest_id: 'abc306',
    problem_index: 'C',
    name: 'Centers',
    title: 'C. Centers',
  },
  {
    id: 'abc306_b',
    contest_id: 'abc306',
    problem_index: 'B',
    name: 'Base 2',
    title: 'B. Base 2',
  },
  {
    id: 'abc306_a',
    contest_id: 'abc306',
    problem_index: 'A',
    name: 'Echo',
    title: 'A. Echo',
    grade: 'Q8',
  },
  {
    id: 'abc305_h',
    contest_id: 'abc305',
    problem_index: 'Ex',
    name: 'Shojin',
    title: 'Ex. Shojin',
  },
  {
    id: 'abc305_g',
    contest_id: 'abc305',
    problem_index: 'G',
    name: 'Banned Substrings',
    title: 'G. Banned Substrings',
  },
  {
    id: 'abc305_f',
    contest_id: 'abc305',
    problem_index: 'F',
    name: 'Dungeon Explore',
    title: 'F. Dungeon Explore',
  },
  {
    id: 'abc305_e',
    contest_id: 'abc305',
    problem_index: 'E',
    name: 'Art Gallery on Graph',
    title: 'E. Art Gallery on Graph',
  },
  {
    id: 'abc305_d',
    contest_id: 'abc305',
    problem_index: 'D',
    name: 'Sleep Log',
    title: 'D. Sleep Log',
  },
  {
    id: 'abc305_c',
    contest_id: 'abc305',
    problem_index: 'C',
    name: 'Snuke the Cookie Picker',
    title: 'C. Snuke the Cookie Picker',
  },
  {
    id: 'abc305_b',
    contest_id: 'abc305',
    problem_index: 'B',
    name: 'ABCDEFG',
    title: 'B. ABCDEFG',
  },
  {
    id: 'abc305_a',
    contest_id: 'abc305',
    problem_index: 'A',
    name: 'Water Station',
    title: 'A. Water Station',
    grade: 'Q7',
  },
  {
    id: 'abc304_h',
    contest_id: 'abc304',
    problem_index: 'Ex',
    name: 'Constrained Topological Sort',
    title: 'Ex. Constrained Topological Sort',
  },
  {
    id: 'abc304_g',
    contest_id: 'abc304',
    problem_index: 'G',
    name: 'Max of Medians',
    title: 'G. Max of Medians',
  },
  {
    id: 'abc304_f',
    contest_id: 'abc304',
    problem_index: 'F',
    name: 'Shift Table',
    title: 'F. Shift Table',
  },
  {
    id: 'abc304_e',
    contest_id: 'abc304',
    problem_index: 'E',
    name: 'Good Graph',
    title: 'E. Good Graph',
  },
  {
    id: 'abc304_d',
    contest_id: 'abc304',
    problem_index: 'D',
    name: 'A Piece of Cake',
    title: 'D. A Piece of Cake',
  },
  {
    id: 'abc304_c',
    contest_id: 'abc304',
    problem_index: 'C',
    name: 'Virus',
    title: 'C. Virus',
  },
  {
    id: 'abc304_b',
    contest_id: 'abc304',
    problem_index: 'B',
    name: 'Subscribers',
    title: 'B. Subscribers',
  },
  {
    id: 'abc304_a',
    contest_id: 'abc304',
    problem_index: 'A',
    name: 'First Player',
    title: 'A. First Player',
    grade: 'Q7',
  },
  {
    id: 'abc303_h',
    contest_id: 'abc303',
    problem_index: 'Ex',
    name: 'Constrained Tree Degree',
    title: 'Ex. Constrained Tree Degree',
  },
  {
    id: 'abc303_g',
    contest_id: 'abc303',
    problem_index: 'G',
    name: 'Bags Game',
    title: 'G. Bags Game',
  },
  {
    id: 'abc303_f',
    contest_id: 'abc303',
    problem_index: 'F',
    name: 'Damage over Time',
    title: 'F. Damage over Time',
  },
  {
    id: 'abc303_e',
    contest_id: 'abc303',
    problem_index: 'E',
    name: 'A Gift From the Stars',
    title: 'E. A Gift From the Stars',
  },
  {
    id: 'abc303_d',
    contest_id: 'abc303',
    problem_index: 'D',
    name: 'Shift vs. CapsLock',
    title: 'D. Shift vs. CapsLock',
  },
  {
    id: 'abc303_c',
    contest_id: 'abc303',
    problem_index: 'C',
    name: 'Dash',
    title: 'C. Dash',
  },
  {
    id: 'abc303_b',
    contest_id: 'abc303',
    problem_index: 'B',
    name: 'Discord',
    title: 'B. Discord',
  },
  {
    id: 'abc303_a',
    contest_id: 'abc303',
    problem_index: 'A',
    name: 'Similar String',
    title: 'A. Similar String',
    grade: 'Q7',
  },
  {
    id: 'abc302_h',
    contest_id: 'abc302',
    problem_index: 'Ex',
    name: 'Ball Collector',
    title: 'Ex. Ball Collector',
  },
  {
    id: 'abc302_g',
    contest_id: 'abc302',
    problem_index: 'G',
    name: 'Sort from 1 to 4',
    title: 'G. Sort from 1 to 4',
  },
  {
    id: 'abc302_f',
    contest_id: 'abc302',
    problem_index: 'F',
    name: 'Merge Set',
    title: 'F. Merge Set',
  },
  {
    id: 'abc302_e',
    contest_id: 'abc302',
    problem_index: 'E',
    name: 'Isolation',
    title: 'E. Isolation',
  },
  {
    id: 'abc302_d',
    contest_id: 'abc302',
    problem_index: 'D',
    name: 'Impartial Gift',
    title: 'D. Impartial Gift',
  },
  {
    id: 'abc302_c',
    contest_id: 'abc302',
    problem_index: 'C',
    name: 'Almost Equal',
    title: 'C. Almost Equal',
  },
  {
    id: 'abc302_b',
    contest_id: 'abc302',
    problem_index: 'B',
    name: 'Find snuke',
    title: 'B. Find snuke',
  },
  {
    id: 'abc302_a',
    contest_id: 'abc302',
    problem_index: 'A',
    name: 'Attack',
    title: 'A. Attack',
    grade: 'Q7',
  },
  {
    id: 'abc301_h',
    contest_id: 'abc301',
    problem_index: 'Ex',
    name: 'Difference of Distance',
    title: 'Ex. Difference of Distance',
  },
  {
    id: 'abc301_g',
    contest_id: 'abc301',
    problem_index: 'G',
    name: 'Worst Picture',
    title: 'G. Worst Picture',
  },
  {
    id: 'abc301_f',
    contest_id: 'abc301',
    problem_index: 'F',
    name: 'Anti-DDoS',
    title: 'F. Anti-DDoS',
  },
  {
    id: 'abc301_e',
    contest_id: 'abc301',
    problem_index: 'E',
    name: 'Pac-Takahashi ',
    title: 'E. Pac-Takahashi ',
  },
  {
    id: 'abc301_d',
    contest_id: 'abc301',
    problem_index: 'D',
    name: 'Bitmask',
    title: 'D. Bitmask',
  },
  {
    id: 'abc301_c',
    contest_id: 'abc301',
    problem_index: 'C',
    name: 'AtCoder Cards',
    title: 'C. AtCoder Cards',
  },
  {
    id: 'abc301_b',
    contest_id: 'abc301',
    problem_index: 'B',
    name: ' Fill the Gaps',
    title: 'B.  Fill the Gaps',
  },
  {
    id: 'abc301_a',
    contest_id: 'abc301',
    problem_index: 'A',
    name: 'Overall Winner',
    title: 'A. Overall Winner',
    grade: 'Q7',
  },
  {
    id: 'abc300_h',
    contest_id: 'abc300',
    problem_index: 'Ex',
    name: 'Fibonacci: Revisited',
    title: 'Ex. Fibonacci: Revisited',
  },
  {
    id: 'abc300_g',
    contest_id: 'abc300',
    problem_index: 'G',
    name: 'P-smooth number',
    title: 'G. P-smooth number',
  },
  {
    id: 'abc300_f',
    contest_id: 'abc300',
    problem_index: 'F',
    name: 'More Holidays',
    title: 'F. More Holidays',
  },
  {
    id: 'abc300_e',
    contest_id: 'abc300',
    problem_index: 'E',
    name: 'Dice Product 3',
    title: 'E. Dice Product 3',
  },
  {
    id: 'abc300_d',
    contest_id: 'abc300',
    problem_index: 'D',
    name: 'AABCC',
    title: 'D. AABCC',
  },
  {
    id: 'abc300_c',
    contest_id: 'abc300',
    problem_index: 'C',
    name: 'Cross',
    title: 'C. Cross',
  },
  {
    id: 'abc300_b',
    contest_id: 'abc300',
    problem_index: 'B',
    name: 'Same Map in the RPG World',
    title: 'B. Same Map in the RPG World',
  },
  {
    id: 'abc300_a',
    contest_id: 'abc300',
    problem_index: 'A',
    name: 'N-choice question',
    title: 'A. N-choice question',
    grade: 'Q8',
  },
];
